spring:
  datasource:
      url: jdbc:mysql://60.205.191.136:3306/hj_eighteen_c?characterEncoding=utf8&useSSL=false
      username: hj_eighteen_c
      password: ESwsKtarmfKWJcrL
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.wangff.learning.api.model
  mapper-locations: classpath:mapper/*.xml

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql